### ISSUE TITLE
Change theme dependent on time (of day)

### ISSUE THREAD

**Issue by tbrodbeck** [jtpio/jupyterlab-theme-toggle#10]
This is another feature request:
It would be great if the theme could be changed automatically dependent on the time of day (or alternatively dependent on the theme of the OS - as it is common in macOS).

**Comment by jtpio** [comment]
Thanks @tbrodbeck for the suggestion!

> or alternatively dependent on the theme of the OS 

There is a similar issue in the JupyterLab repo: https://github.com/jupyterlab/jupyterlab/issues/8777

But it would indeed be useful to try it in a third-party extension like this one first.

Would you like to give it a try in a PR, maybe by following some of the hints from https://github.com/jupyterlab/jupyterlab/issues/8777?

**Comment by jtpio** [comment]
Closing as tracked in https://github.com/jupyterlab/jupyterlab/issues/8777

And there is now a draft PR to address the issue: https://github.com/jupyterlab/jupyterlab/pull/14808
